from __future__ import annotations

import re
from pathlib import Path

from fw_diag_tool.analyzers.register_mapper import RegisterMapCatalog


class CHeaderGenerator:
    # Generates MISRA-compliant C register definitions and bitfield RMW macros

    def __init__(self, catalog: RegisterMapCatalog | None = None):
        self.catalog = catalog or RegisterMapCatalog()

    @classmethod
    def from_yaml_file(cls, yaml_path: str | Path) -> CHeaderGenerator:
        p = Path(yaml_path)
        gen = cls()
        gen.catalog.load_from_yaml(p.read_text(encoding="utf-8"))
        return gen

    @classmethod
    def from_yaml_str(cls, yaml_content: str) -> CHeaderGenerator:
        gen = cls()
        gen.catalog.load_from_yaml(yaml_content)
        return gen

    @staticmethod
    def _sanitize_name(name: str) -> str:
        s = re.sub(r"[^A-Za-z0-9_]", "_", name.strip())
        return s.upper()

    def generate_header(self, module_name: str = "CHIP_REGS") -> str:
        guard_name = f"_{self._sanitize_name(module_name)}_H_"
        lines: list[str] = [
            "/**",
            f" * @file {module_name.lower()}.h",
            " * @brief Auto-generated Hardware Register Bitfield Definitions & RMW Macros",
            " * @generated by fw-diag-tool (Firmware Diagnostic Toolkit)",
            " * @note Do NOT edit manually unless necessary.",
            " */",
            "",
            f"#ifndef {guard_name}",
            f"#define {guard_name}",
            "",
            "#include <stdint.h>",
            "",
            "/* ========================================================================= */",
            "/*                      REGISTER OFFSETS & MASKS                             */",
            "/* ========================================================================= */",
            "",
        ]

        for offset, reg in sorted(self.catalog.registers.items()):
            r_name = self._sanitize_name(reg.name)
            desc_comment = f" /* {reg.description} */" if reg.description else ""
            lines.append(f"/* Register: {r_name} (0x{reg.offset:04X}){desc_comment} */")
            lines.append(f"#define REG_{r_name}_OFFSET              (0x{reg.offset:04X}U)")
            if reg.reset_val:
                lines.append(f"#define REG_{r_name}_RESET               (0x{reg.reset_val:08X}U)")
            lines.append("")

            for f in reg.fields:
                f_name = self._sanitize_name(f.name)
                pos = f.low_bit
                mask = f.bit_mask
                lines.append(f"#define REG_{r_name}_{f_name}_POS        ({pos}U)")
                lines.append(f"#define REG_{r_name}_{f_name}_MSK        (0x{mask:08X}U)")
                lines.append(
                    f"#define REG_{r_name}_{f_name}_GET(val)   (((val) & REG_{r_name}_{f_name}_MSK) >> REG_{r_name}_{f_name}_POS)"
                )
                lines.append(
                    f"#define REG_{r_name}_{f_name}_SET(reg, val) (((reg) & ~REG_{r_name}_{f_name}_MSK) | (((uint32_t)(val) << REG_{r_name}_{f_name}_POS) & REG_{r_name}_{f_name}_MSK))"
                )

                if f.values:
                    lines.append(f"/* Values for {r_name}.{f_name} */")
                    for val_int, val_meaning in sorted(f.values.items()):
                        v_label = self._sanitize_name(val_meaning)
                        lines.append(f"#define VAL_{r_name}_{f_name}_{v_label} ({val_int}U)")
                lines.append("")

            lines.append(
                "/* ------------------------------------------------------------------------- */"
            )
            lines.append("")

        lines.append(f"#endif /* {guard_name} */")
        lines.append("")
        return "\n".join(lines)
