from __future__ import annotations

from typing import Any

COMPATIBLE_MAP = {
    "EEPROM": ("atmel,24c64", "pagesize = <32>;"),
    "Temperature Sensor": ("national,lm75", ""),
    "Power Monitor": ("ti,ina226", "shunt-resistor = <1000>; /* 1 mOhm */"),
    "PMBus": ("pmbus", ""),
    "GPIO Expander": ("nxp,pca9555", "gpio-controller;\n                #gpio-cells = <2>;"),
    "I2C Multiplexer": ("nxp,pca9548", ""),
}


class DeviceTreeGenerator:
    # Generates Linux Kernel and OpenBMC compliant Device Tree (.dts) nodes from topology

    @classmethod
    def generate_dts_from_topology(
        cls,
        bus_num: int = 1,
        mux_addr: int = 0x70,
        devices: list[dict[str, Any]] | None = None,
        node_name: str = "i2c_bus"
    ) -> str:
        devs = devices or [
            {"addr": 0x50, "type": "EEPROM", "channel": 0, "name": "eeprom"},
            {"addr": 0x48, "type": "Temperature Sensor", "channel": 1, "name": "temp_sensor"},
            {"addr": 0x40, "type": "Power Monitor", "channel": 2, "name": "power_monitor"},
            {"addr": 0x58, "type": "PMBus", "channel": 3, "name": "vr_controller"},
        ]

        lines = [
            "// SPDX-License-Identifier: GPL-2.0+ or MIT",
            "/*",
            " * Auto-generated Linux / OpenBMC Device Tree Source (.dts)",
            " * Generated by fw-diag-tool (Firmware Diagnostic Toolkit)",
            " */",
            "",
            f"&i2c{bus_num} {{",
            "    status = \"okay\";",
            "    bus-frequency = <400000>;",
            "",
            f"    i2c-mux@{mux_addr:x} {{",
            "        compatible = \"nxp,pca9548\";",
            f"        reg = <0x{mux_addr:02x}>;",
            "        #address-cells = <1>;",
            "        #size-cells = <0>;",
            "        i2c-mux-idle-disconnect;",
            "",
        ]

        # Group devices by MUX channel 0..7
        channels: dict[int, list[dict[str, Any]]] = {ch: [] for ch in range(8)}
        for d in devs:
            ch = d.get("channel", 0)
            channels.setdefault(ch, []).append(d)

        for ch in range(8):
            ch_devs = channels.get(ch, [])
            lines.append(f"        i2c@{ch} {{")
            lines.append("            #address-cells = <1>;")
            lines.append("            #size-cells = <0>;")
            lines.append(f"            reg = <{ch}>;")
            lines.append("")
            for d in ch_devs:
                d_addr = d["addr"]
                d_type = d.get("type", "EEPROM")
                d_name = d.get("name", "dev").replace(" ", "_").lower()
                compat, extra = COMPATIBLE_MAP.get(d_type, ("generic,i2c-device", ""))
                lines.append(f"            {d_name}@{d_addr:x} {{")
                lines.append(f"                compatible = \"{compat}\";")
                lines.append(f"                reg = <0x{d_addr:02x}>;")
                if extra:
                    for ex_line in extra.splitlines():
                        lines.append(f"                {ex_line}")
                lines.append("            };")
                lines.append("")
            lines.append("        };")
            lines.append("")

        lines.append("    };")
        lines.append("};")
        lines.append("")
        return "\n".join(lines)