from __future__ import annotations

import re

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .models import UARTReport

_CRASH_TYPE_ZH = {
    "Linux Kernel Panic / Oops": "Linux 核心 Panic／Oops（Linux Kernel Panic / Oops）",
    "ARM Cortex-M HardFault": "ARM Cortex-M HardFault 例外（ARM Cortex-M HardFault）",
    "Hardware Watchdog Timeout Reset": "硬體 Watchdog 逾時重置（Hardware Watchdog Timeout Reset）",
    "Generic Serial Log / Boot Trace": "一般序列埠 Log／開機追蹤（Generic Serial Log / Boot Trace）",
}

_FAULT_FLAG_ZH = {
    "HFSR.FORCED (HardFault generated by escalation of a configurable fault)": "HFSR.FORCED（設定型 fault 升級後產生 HardFault）",
    "HFSR.VECTTBL (Vector Table Read Fault on Exception Processing)": "HFSR.VECTTBL（例外處理期間讀取 Vector Table 發生 fault）",
    "UFSR.DIVBYZERO (Division by Zero trapped)": "UFSR.DIVBYZERO（捕捉到除以零）",
    "UFSR.UNALIGNED (Unaligned memory access trapped)": "UFSR.UNALIGNED（捕捉到未對齊記憶體存取）",
    "UFSR.NOCP (No Coprocessor / FPU Access Fault)": "UFSR.NOCP（協處理器／FPU 存取 fault）",
    "UFSR.INVSTATE (Invalid EPSR/Thumb State Fault)": "UFSR.INVSTATE（EPSR／Thumb 狀態無效）",
    "UFSR.UNDEFINSTR (Undefined instruction executed)": "UFSR.UNDEFINSTR（執行未定義指令）",
    "BFSR.LSPERR (BusFault during FP lazy state preservation)": "BFSR.LSPERR（FP lazy state 保存期間發生 BusFault）",
    "BFSR.STKERR (BusFault on stacking for exception)": "BFSR.STKERR（例外堆疊期間發生 BusFault）",
    "BFSR.UNSTKERR (BusFault on unstacking for exception)": "BFSR.UNSTKERR（例外取消堆疊期間發生 BusFault）",
    "BFSR.IMPRECISERR (Imprecise Data Bus Error - asynchronous bus write fault)": "BFSR.IMPRECISERR（非精確資料匯流排錯誤－非同步寫入 fault）",
    "BFSR.IBUSERR (Instruction Bus Error on branch/prefetch)": "BFSR.IBUSERR（分支／預取期間發生指令匯流排錯誤）",
    "MMFSR.MLSPERR (MemManage fault during FP lazy state preservation)": "MMFSR.MLSPERR（FP lazy state 保存期間發生 MemManage fault）",
    "MMFSR.MSTKERR (MemManage fault on stacking for exception)": "MMFSR.MSTKERR（例外堆疊期間發生 MemManage fault）",
    "MMFSR.MUNSTKERR (MemManage fault on unstacking for exception)": "MMFSR.MUNSTKERR（例外取消堆疊期間發生 MemManage fault）",
    "MMFSR.DACCVIOL (Data Access Violation / MPU Fault)": "MMFSR.DACCVIOL（資料存取違規／MPU fault）",
    "MMFSR.IACCVIOL (Instruction Access Violation / MPU Fault)": "MMFSR.IACCVIOL（指令存取違規／MPU fault）",
    "UFSR.INVPC (Invalid PC load / EXC_RETURN)": "UFSR.INVPC（PC 載入無效／EXC_RETURN）",
}


def _localize_crash_type(value: str) -> str:
    return _CRASH_TYPE_ZH.get(value, value)


def _localize_fault_flag(value: str) -> str:
    translated = _FAULT_FLAG_ZH.get(value)
    if translated:
        return translated
    match = re.fullmatch(r"(BFSR\.BFARVALID) \(Fault Address: (.+)\)", value)
    if match:
        return f"{match.group(1)}（Fault Address：{match.group(2)}）"
    match = re.fullmatch(r"(MMFSR\.MMARVALID) \(Fault Address: (.+)\)", value)
    if match:
        return f"{match.group(1)}（Fault Address：{match.group(2)}）"
    match = re.fullmatch(r"(BFSR\.PRECISERR) \(Precise Data Bus Error at address: (.+)\)", value)
    if match:
        return f"{match.group(1)}（精確資料匯流排錯誤，位址：{match.group(2)}）"
    return value


def _localize_hardfault_summary(value: str) -> str:
    if value == "ARM Cortex-M HardFault Exception Triggered.":
        return "ARM Cortex-M HardFault 例外已觸發（ARM Cortex-M HardFault Exception Triggered.）"
    return value


class UARTReporter:
    @staticmethod
    def render_terminal(report: UARTReport, console: Console | None = None) -> None:
        c = console or Console()
        c.print(
            Panel(
                f"[bold red]⚡ UART 崩潰轉儲與 HardFault 診斷報告（UART Crash & HardFault Diagnostic Report）[/]\n"
                f"類型（Type）: [yellow]{_localize_crash_type(report.crash_type.value)}[/]"
            )
        )

        if not report.kernel_panic and not report.arm_hardfault:
            c.print(
                Panel(
                    "[yellow]未辨識 Crash Signature（未偵測到已支援的 Kernel Panic / HardFault 標記）[/]\n"
                    f"原始日誌行數（Raw Log Lines）: {report.raw_log_lines}\n"
                    "下一步：保留完整 UART log，確認內容包含支援的 Kernel Panic、Oops、HardFault 或暫存器標記。",
                    border_style="yellow",
                )
            )
            return

        if report.kernel_panic:
            kp = report.kernel_panic
            sum_tbl = Table(title="Kernel Panic 摘要（Kernel Panic Summary）", show_header=True)
            sum_tbl.add_column("欄位（Field）", style="cyan")
            sum_tbl.add_column("值（Value）", style="bold white")
            sum_tbl.add_row("架構（Architecture）", kp.architecture)
            sum_tbl.add_row("Panic 原因（Panic Reason）", kp.panic_reason)
            if kp.faulting_ip:
                sum_tbl.add_row("故障 IP／RIP（Faulting IP / RIP）", kp.faulting_ip)
            if kp.faulting_func:
                sum_tbl.add_row("故障函式（Faulting Function）", kp.faulting_func)
            if kp.faulting_address:
                sum_tbl.add_row("故障記憶體位址（Faulting Memory Address）", kp.faulting_address)
            if kp.modules_linked:
                sum_tbl.add_row("已連結模組（Modules Linked In）", ", ".join(kp.modules_linked))
            c.print(sum_tbl)

            if kp.call_trace:
                trace_tbl = Table(
                    title="呼叫追蹤／堆疊框架（Call Trace / Stack Frames）", show_header=True
                )
                trace_tbl.add_column("#", justify="right", style="dim")
                trace_tbl.add_column("函式（Function）", style="bold cyan")
                trace_tbl.add_column("位移（Offset）", style="yellow")
                trace_tbl.add_column("模組（Module）", style="green")
                for frame in kp.call_trace:
                    trace_tbl.add_row(
                        str(frame.index),
                        frame.function_name,
                        frame.offset,
                        frame.module or "[kernel]",
                    )
                c.print(trace_tbl)

            chk_str = "\n".join(f"- ✔ {chk}" for chk in kp.actionable_checklist)
            c.print(
                Panel(
                    f"[bold yellow]根因分析（Root Cause Analysis）:[/]\n{kp.root_cause_analysis}\n\n"
                    f"[bold green]可執行除錯清單（Actionable Debug Checklist）:[/]\n{chk_str}",
                    border_style="red",
                )
            )

        elif report.arm_hardfault:
            hf = report.arm_hardfault
            hf_tbl = Table(
                title="ARM Cortex-M HardFault 暫存器（ARM Cortex-M HardFault Registers）",
                show_header=True,
            )
            hf_tbl.add_column("暫存器（Register）", style="cyan")
            hf_tbl.add_column("十六進位值（Hex Value）", style="bold white")
            hf_tbl.add_row("HFSR", f"0x{hf.hfsr_raw:08X}")
            hf_tbl.add_row(
                "CFSR (UFSR/BFSR/MMFSR)",
                f"0x{hf.cfsr_raw:08X} (U:0x{hf.ufsr_raw:04X} B:0x{hf.bfsr_raw:02X} M:0x{hf.mmfsr_raw:02X})",
            )
            if hf.pc_faulting is not None:
                hf_tbl.add_row("故障 PC（Faulting PC）", f"0x{hf.pc_faulting:08X}")
            if hf.lr_exc_return is not None:
                hf_tbl.add_row("LR（EXC_RETURN）", f"0x{hf.lr_exc_return:08X}")
            if hf.bfar_raw is not None:
                hf_tbl.add_row("BFAR", f"0x{hf.bfar_raw:08X}")
            if hf.mmfar_raw is not None:
                hf_tbl.add_row("MMFAR", f"0x{hf.mmfar_raw:08X}")
            c.print(hf_tbl)

            if hf.fault_flags:
                flags_text = "\n".join(f"- ⚠ {_localize_fault_flag(flag)}" for flag in hf.fault_flags)
                c.print(
                    Panel(
                        f"[bold yellow]Fault 旗標（Fault Flags）:[/]\n{flags_text}",
                        border_style="yellow",
                    )
                )
            chk_str = "\n".join(f"- ✔ {chk}" for chk in hf.actionable_checklist)
            c.print(
                Panel(
                    f"[bold yellow]根因分析（Root Cause Analysis）:[/]\n"
                    f"{_localize_hardfault_summary(hf.root_cause_analysis)}\n\n"
                    f"[bold green]行動清單（Actionable Checklist）:[/]\n{chk_str}",
                    border_style="red",
                )
            )

    @staticmethod
    def to_markdown(report: UARTReport) -> str:
        lines = [
            (
                "# UART 崩潰轉儲分析（UART Crash Dump Analysis）: "
                f"{_localize_crash_type(report.crash_type.value)}\n"
            )
        ]
        if report.kernel_panic:
            kp = report.kernel_panic
            lines.append("## 1. 崩潰摘要（Crash Summary）")
            lines.append(f"- **架構（Architecture）**: `{kp.architecture}`")
            lines.append(f"- **Panic 原因（Panic Reason）**: `{kp.panic_reason}`")
            if kp.faulting_ip:
                lines.append(
                    f"- **故障 IP（Faulting IP）**: `{kp.faulting_ip}` "
                    f"({kp.faulting_func or 'N/A'})"
                )
            if kp.faulting_address:
                lines.append(f"- **故障位址（Faulting Address）**: `{kp.faulting_address}`")
            if kp.modules_linked:
                lines.append(
                    f"- **已連結模組（Modules Linked In）**: `{', '.join(kp.modules_linked)}`"
                )
            lines.append("")
            if kp.call_trace:
                lines.append("## 2. 呼叫追蹤（Call Trace）")
                lines.append("| # | 函式（Function） | 位移（Offset） | 模組（Module） |")
                lines.append("|---|---|---|---|")
                for f in kp.call_trace:
                    lines.append(
                        f"| #{f.index} | `{f.function_name}` | `{f.offset}` | `{f.module or 'kernel'}` |"
                    )
                lines.append("")
            lines.append("## 3. 根因分析與除錯清單（Root Cause Analysis & Debug Checklist）")
            lines.append(f"```text\n{kp.root_cause_analysis}\n```\n")
            for chk in kp.actionable_checklist:
                lines.append(f"- [ ] {chk}")
        elif report.arm_hardfault:
            hf = report.arm_hardfault
            lines.append("## 1. HardFault 暫存器（HardFault Registers）")
            lines.append(f"- **HFSR**: `0x{hf.hfsr_raw:08X}`")
            lines.append(
                f"- **CFSR**: `0x{hf.cfsr_raw:08X}` (UFSR: `0x{hf.ufsr_raw:04X}`, BFSR: `0x{hf.bfsr_raw:02X}`, MMFSR: `0x{hf.mmfsr_raw:02X}`)"
            )
            if hf.pc_faulting is not None:
                lines.append(f"- **故障 PC（Faulting PC）**: `0x{hf.pc_faulting:08X}`")
            if hf.bfar_raw is not None:
                lines.append(f"- **故障位址暫存器（BFAR）**: `0x{hf.bfar_raw:08X}`")
            if hf.mmfar_raw is not None:
                lines.append(f"- **記憶體管理故障位址（MMFAR）**: `0x{hf.mmfar_raw:08X}`")
            lines.append("")
            lines.append("## 2. Fault Flags 與根因（Fault Flags & Root Cause）")
            for fl in hf.fault_flags:
                lines.append(f"- ⚠️ {_localize_fault_flag(fl)}")
            lines.append(f"\n```text\n{_localize_hardfault_summary(hf.root_cause_analysis)}\n```\n")
            for chk in hf.actionable_checklist:
                lines.append(f"- [ ] {chk}")
        else:
            lines.extend(
                [
                    "## 1. 未辨識 Crash Signature（Unsupported Crash Signature）",
                    "- **狀態（Status）**: 未偵測到已支援的 Kernel Panic / HardFault 標記。",
                    f"- **原始日誌行數（Raw Log Lines）**: `{report.raw_log_lines}`",
                    "",
                    "## 2. 建議下一步（Next Step）",
                    "- 保留完整 UART log，確認內容包含 Kernel Panic、Oops、HardFault 或相關暫存器標記。",
                ]
            )
        return "\n".join(lines)
