from __future__ import annotations

import re
from typing import TYPE_CHECKING

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from .models import UARTReport
from .symptom_db import MatchedSymptom, classify_symptoms

if TYPE_CHECKING:
    from .timing import UARTTimingAnalysis

_CRASH_TYPE_ZH = {
    "Linux Kernel Panic / Oops": "Linux 核心 Panic／Oops（Linux Kernel Panic / Oops）",
    "ARM Cortex-M HardFault": "ARM Cortex-M HardFault 例外（ARM Cortex-M HardFault）",
    "Hardware Watchdog Timeout Reset": "硬體 Watchdog 逾時重置（Hardware Watchdog Timeout Reset）",
    "Generic Serial Log / Boot Trace": "一般序列埠 Log／開機追蹤（Generic Serial Log / Boot Trace）",
}

_FAULT_FLAG_ZH = {
    "HFSR.FORCED (HardFault generated by escalation of a configurable fault)": "HFSR.FORCED（設定型 fault 升級後產生 HardFault）",
    "HFSR.VECTTBL (Vector Table Read Fault on Exception Processing)": "HFSR.VECTTBL（例外處理期間讀取 Vector Table 發生 fault）",
    "UFSR.DIVBYZERO (Division by Zero trapped)": "UFSR.DIVBYZERO（捕捉到除以零）",
    "UFSR.UNALIGNED (Unaligned memory access trapped)": "UFSR.UNALIGNED（捕捉到未對齊記憶體存取）",
    "UFSR.NOCP (No Coprocessor / FPU Access Fault)": "UFSR.NOCP（協處理器／FPU 存取 fault）",
    "UFSR.INVSTATE (Invalid EPSR/Thumb State Fault)": "UFSR.INVSTATE（EPSR／Thumb 狀態無效）",
    "UFSR.UNDEFINSTR (Undefined instruction executed)": "UFSR.UNDEFINSTR（執行未定義指令）",
    "BFSR.LSPERR (BusFault during FP lazy state preservation)": "BFSR.LSPERR（FP lazy state 保存期間發生 BusFault）",
    "BFSR.STKERR (BusFault on stacking for exception)": "BFSR.STKERR（例外堆疊期間發生 BusFault）",
    "BFSR.UNSTKERR (BusFault on unstacking for exception)": "BFSR.UNSTKERR（例外取消堆疊期間發生 BusFault）",
    "BFSR.IMPRECISERR (Imprecise Data Bus Error - asynchronous bus write fault)": "BFSR.IMPRECISERR（非精確資料匯流排錯誤－非同步寫入 fault）",
    "BFSR.IBUSERR (Instruction Bus Error on branch/prefetch)": "BFSR.IBUSERR（分支／預取期間發生指令匯流排錯誤）",
    "MMFSR.MLSPERR (MemManage fault during FP lazy state preservation)": "MMFSR.MLSPERR（FP lazy state 保存期間發生 MemManage fault）",
    "MMFSR.MSTKERR (MemManage fault on stacking for exception)": "MMFSR.MSTKERR（例外堆疊期間發生 MemManage fault）",
    "MMFSR.MUNSTKERR (MemManage fault on unstacking for exception)": "MMFSR.MUNSTKERR（例外取消堆疊期間發生 MemManage fault）",
    "MMFSR.DACCVIOL (Data Access Violation / MPU Fault)": "MMFSR.DACCVIOL（資料存取違規／MPU fault）",
    "MMFSR.IACCVIOL (Instruction Access Violation / MPU Fault)": "MMFSR.IACCVIOL（指令存取違規／MPU fault）",
    "UFSR.INVPC (Invalid PC load / EXC_RETURN)": "UFSR.INVPC（PC 載入無效／EXC_RETURN）",
}

_PANIC_REASON_REPLACEMENTS = (
    (
        "BUG: unable to handle page fault for address:",
        "BUG：無法處理 page fault（分頁錯誤），位址：",
    ),
    (
        "Kernel panic - not syncing:",
        "Kernel panic（核心 Panic）：未同步：",
    ),
    (
        "Fatal exception in interrupt",
        "中斷期間發生致命例外（Fatal exception in interrupt）",
    ),
    (
        "Internal error: synchronous external abort:",
        "內部錯誤（Internal error）：同步 external abort（synchronous external abort）：",
    ),
    ("Internal error:", "內部錯誤（Internal error）："),
    (
        "Unable to handle kernel paging request at virtual address",
        "無法處理核心 paging request（kernel paging request），虛擬位址：",
    ),
)

_ANALYSIS_TEXT_REPLACEMENTS = (
    (
        "NULL Pointer Dereference 候選",
        "NULL 指標解引用候選（NULL Pointer Dereference）",
    ),
    ("Kernel Exception", "核心例外（Kernel Exception）"),
    ("Stack Corruption", "堆疊損毀（Stack Corruption）"),
    ("fault context", "故障上下文（fault context）"),
    ("總線錯誤", "匯流排錯誤"),
    ("總線", "匯流排"),
    (" (位址:", "（位址："),
)

_CHECKLIST_TEXT_REPLACEMENTS = (
    ("Call Trace", "Call Trace（呼叫追蹤）"),
    ("Stack Corruption", "堆疊損毀（Stack Corruption）"),
)


def _localize_crash_type(value: str) -> str:
    return _CRASH_TYPE_ZH.get(value, value)


def _localize_panic_reason(value: str) -> str:
    """Translate known kernel panic prose while retaining the source line."""
    if not value:
        return value
    localized = value.strip()
    for source, target in _PANIC_REASON_REPLACEMENTS:
        localized = localized.replace(source, target)
    if localized == value.strip():
        return value
    return f"{localized}（原文：{value.strip()}）"


def _localize_analysis_text(value: str) -> str:
    """Translate analyzer prose without changing symbols, expressions, or values."""
    if not value:
        return value
    lines = []
    for line in value.splitlines():
        localized = line
        for source, target in _ANALYSIS_TEXT_REPLACEMENTS:
            localized = localized.replace(source, target)
        lines.append(localized)
    return "\n".join(lines)


def _localize_checklist_item(value: str) -> str:
    if not value:
        return value
    localized = value
    for source, target in _CHECKLIST_TEXT_REPLACEMENTS:
        localized = localized.replace(source, target)
    return localized


def _localize_fault_flag(value: str) -> str:
    translated = _FAULT_FLAG_ZH.get(value)
    if translated:
        return translated
    match = re.fullmatch(r"(BFSR\.BFARVALID) \(Fault Address: (.+)\)", value)
    if match:
        return f"{match.group(1)}（Fault Address：{match.group(2)}）"
    match = re.fullmatch(r"(MMFSR\.MMARVALID) \(Fault Address: (.+)\)", value)
    if match:
        return f"{match.group(1)}（Fault Address：{match.group(2)}）"
    match = re.fullmatch(r"(BFSR\.PRECISERR) \(Precise Data Bus Error at address: (.+)\)", value)
    if match:
        return f"{match.group(1)}（精確資料匯流排錯誤，位址：{match.group(2)}）"
    return value


def _localize_hardfault_summary(value: str) -> str:
    if value == "ARM Cortex-M HardFault Exception Triggered.":
        return "ARM Cortex-M HardFault 例外已觸發（ARM Cortex-M HardFault Exception Triggered.）"
    return _localize_analysis_text(value)


class UARTReporter:
    @staticmethod
    def render_terminal(
        report: UARTReport,
        console: Console | None = None,
        timing: UARTTimingAnalysis | None = None,
    ) -> None:
        c = console or Console()
        c.print(
            Panel(
                f"[bold red]⚡ UART 崩潰轉儲與 HardFault 診斷報告（UART Crash & HardFault Diagnostic Report）[/]\n"
                f"類型（Type）: [yellow]{_localize_crash_type(report.crash_type.value)}[/]"
            )
        )

        if not report.kernel_panic and not report.arm_hardfault:
            c.print(
                Panel(
                    "[yellow]未辨識 Crash Signature（未偵測到已支援的 Kernel Panic / HardFault 標記）[/]\n"
                    f"原始日誌行數（Raw Log Lines）: {report.raw_log_lines}\n"
                    "下一步：保留完整 UART log，確認內容包含支援的 Kernel Panic、Oops、HardFault 或暫存器標記。",
                    border_style="yellow",
                )
            )
            effective_timing = timing or getattr(report, "timing", None)
            if effective_timing is not None:
                timing_tbl = Table(
                    title="UART 時序分析摘要（UART Timing Summary）",
                    show_header=True,
                )
                timing_tbl.add_column("項目（Item）", style="cyan")
                timing_tbl.add_column("值（Value）", style="bold white")
                timing_tbl.add_row(
                    "總記錄時間（Total Log Duration）",
                    f"{effective_timing.total_log_duration_s:.3f} 秒"
                    if effective_timing.total_log_duration_s is not None
                    else "N/A",
                )
                timing_tbl.add_row(
                    "時間戳覆蓋率（Timestamp Coverage）",
                    f"{effective_timing.timestamp_coverage * 100:.1f}%",
                )
                timing_tbl.add_row(
                    "原始日誌行數（Line Count）",
                    f"{effective_timing.line_count}",
                )
                bl_dur = effective_timing.boot_phase_durations.get("bootloader")
                k_dur = effective_timing.boot_phase_durations.get("kernel")
                us_dur = effective_timing.boot_phase_durations.get("userspace")
                timing_tbl.add_row(
                    "Bootloader 耗時",
                    f"{bl_dur:.3f} 秒" if bl_dur is not None else "N/A",
                )
                timing_tbl.add_row(
                    "Kernel 耗時",
                    f"{k_dur:.3f} 秒" if k_dur is not None else "N/A",
                )
                timing_tbl.add_row(
                    "Userspace 耗時",
                    f"{us_dur:.3f} 秒" if us_dur is not None else "N/A",
                )
                if effective_timing.crash_to_reset_interval_s is not None:
                    timing_tbl.add_row(
                        "崩潰至重置間隔（Crash-to-Reset Interval）",
                        f"{effective_timing.crash_to_reset_interval_s:.3f} 秒",
                    )
                c.print(timing_tbl)
            return

        if report.kernel_panic:
            kp = report.kernel_panic
            sum_tbl = Table(title="Kernel Panic 摘要（Kernel Panic Summary）", show_header=True)
            sum_tbl.add_column("欄位（Field）", style="cyan")
            sum_tbl.add_column("值（Value）", style="bold white")
            sum_tbl.add_row("架構（Architecture）", kp.architecture)
            sum_tbl.add_row("Panic 原因（Panic Reason）", _localize_panic_reason(kp.panic_reason))
            if kp.faulting_ip:
                sum_tbl.add_row("故障 IP／RIP（Faulting IP / RIP）", kp.faulting_ip)
            if kp.faulting_func:
                sum_tbl.add_row("故障函式（Faulting Function）", kp.faulting_func)
            if kp.faulting_address:
                sum_tbl.add_row("故障記憶體位址（Faulting Memory Address）", kp.faulting_address)
            if kp.modules_linked:
                sum_tbl.add_row("已連結模組（Modules Linked In）", ", ".join(kp.modules_linked))
            c.print(sum_tbl)

            if kp.call_trace:
                trace_tbl = Table(
                    title="呼叫追蹤／堆疊框架（Call Trace / Stack Frames）", show_header=True
                )
                trace_tbl.add_column("#", justify="right", style="dim")
                trace_tbl.add_column("函式（Function）", style="bold cyan")
                trace_tbl.add_column("位移（Offset）", style="yellow")
                trace_tbl.add_column("模組（Module）", style="green")
                for frame in kp.call_trace:
                    trace_tbl.add_row(
                        str(frame.index),
                        frame.function_name,
                        frame.offset,
                        frame.module or "[kernel]",
                    )
                c.print(trace_tbl)

            root_cause = _localize_analysis_text(kp.root_cause_analysis)
            chk_str = "\n".join(
                f"- ✔ {_localize_checklist_item(chk)}" for chk in kp.actionable_checklist
            )
            c.print(
                Panel(
                    f"[bold yellow]根因分析（Root Cause Analysis）:[/]\n{root_cause}\n\n"
                    f"[bold green]可執行除錯清單（Actionable Debug Checklist）:[/]\n{chk_str}",
                    border_style="red",
                )
            )

        elif report.arm_hardfault:
            hf = report.arm_hardfault
            hf_tbl = Table(
                title="ARM Cortex-M HardFault 暫存器（ARM Cortex-M HardFault Registers）",
                show_header=True,
            )
            hf_tbl.add_column("暫存器（Register）", style="cyan")
            hf_tbl.add_column("十六進位值（Hex Value）", style="bold white")
            hf_tbl.add_row("HFSR", f"0x{hf.hfsr_raw:08X}")
            hf_tbl.add_row(
                "CFSR (UFSR/BFSR/MMFSR)",
                f"0x{hf.cfsr_raw:08X} (U:0x{hf.ufsr_raw:04X} B:0x{hf.bfsr_raw:02X} M:0x{hf.mmfsr_raw:02X})",
            )
            if hf.pc_faulting is not None:
                hf_tbl.add_row("故障 PC（Faulting PC）", f"0x{hf.pc_faulting:08X}")
            if hf.lr_exc_return is not None:
                hf_tbl.add_row("LR（EXC_RETURN）", f"0x{hf.lr_exc_return:08X}")
            if hf.bfar_raw is not None:
                hf_tbl.add_row("BFAR", f"0x{hf.bfar_raw:08X}")
            if hf.mmfar_raw is not None:
                hf_tbl.add_row("MMFAR", f"0x{hf.mmfar_raw:08X}")
            c.print(hf_tbl)

            if hf.fault_flags:
                flags_text = "\n".join(
                    f"- ⚠ {_localize_fault_flag(flag)}" for flag in hf.fault_flags
                )
                c.print(
                    Panel(
                        f"[bold yellow]Fault 旗標（Fault Flags）:[/]\n{flags_text}",
                        border_style="yellow",
                    )
                )
            chk_str = "\n".join(
                f"- ✔ {_localize_checklist_item(chk)}" for chk in hf.actionable_checklist
            )
            c.print(
                Panel(
                    f"[bold yellow]根因分析（Root Cause Analysis）:[/]\n"
                    f"{_localize_hardfault_summary(hf.root_cause_analysis)}\n\n"
                    f"[bold green]行動清單（Actionable Checklist）:[/]\n{chk_str}",
                    border_style="red",
                )
            )

        effective_timing = timing or getattr(report, "timing", None)
        if effective_timing is not None:
            timing_tbl = Table(
                title="UART 時序分析摘要（UART Timing Summary）",
                show_header=True,
            )
            timing_tbl.add_column("項目（Item）", style="cyan")
            timing_tbl.add_column("值（Value）", style="bold white")
            timing_tbl.add_row(
                "總記錄時間（Total Log Duration）",
                f"{effective_timing.total_log_duration_s:.3f} 秒"
                if effective_timing.total_log_duration_s is not None
                else "N/A",
            )
            timing_tbl.add_row(
                "時間戳覆蓋率（Timestamp Coverage）",
                f"{effective_timing.timestamp_coverage * 100:.1f}%",
            )
            timing_tbl.add_row(
                "原始日誌行數（Line Count）",
                f"{effective_timing.line_count}",
            )
            bl_dur = effective_timing.boot_phase_durations.get("bootloader")
            k_dur = effective_timing.boot_phase_durations.get("kernel")
            us_dur = effective_timing.boot_phase_durations.get("userspace")
            timing_tbl.add_row(
                "Bootloader 耗時",
                f"{bl_dur:.3f} 秒" if bl_dur is not None else "N/A",
            )
            timing_tbl.add_row(
                "Kernel 耗時",
                f"{k_dur:.3f} 秒" if k_dur is not None else "N/A",
            )
            timing_tbl.add_row(
                "Userspace 耗時",
                f"{us_dur:.3f} 秒" if us_dur is not None else "N/A",
            )
            if effective_timing.crash_to_reset_interval_s is not None:
                timing_tbl.add_row(
                    "崩潰至重置間隔（Crash-to-Reset Interval）",
                    f"{effective_timing.crash_to_reset_interval_s:.3f} 秒",
                )
            c.print(timing_tbl)

    @staticmethod
    def to_markdown(
        report: UARTReport,
        timing: UARTTimingAnalysis | None = None,
        lines: list[str] | None = None,
    ) -> str:
        source_lines = lines
        lines = [
            (
                "# UART 崩潰轉儲分析（UART Crash Dump Analysis）: "
                f"{_localize_crash_type(report.crash_type.value)}\n"
            )
        ]
        if report.kernel_panic:
            kp = report.kernel_panic
            lines.append("## 1. 崩潰摘要（Crash Summary）")
            lines.append(f"- **架構（Architecture）**: `{kp.architecture}`")
            lines.append(
                f"- **Panic 原因（Panic Reason）**: `{_localize_panic_reason(kp.panic_reason)}`"
            )
            if kp.faulting_ip:
                lines.append(
                    f"- **故障 IP（Faulting IP）**: `{kp.faulting_ip}` "
                    f"({kp.faulting_func or 'N/A'})"
                )
            if kp.faulting_address:
                lines.append(f"- **故障位址（Faulting Address）**: `{kp.faulting_address}`")
            if kp.modules_linked:
                lines.append(
                    f"- **已連結模組（Modules Linked In）**: `{', '.join(kp.modules_linked)}`"
                )
            lines.append("")
            if kp.call_trace:
                lines.append("## 2. 呼叫追蹤（Call Trace）")
                lines.append("| # | 函式（Function） | 位移（Offset） | 模組（Module） |")
                lines.append("|---|---|---|---|")
                for f in kp.call_trace:
                    lines.append(
                        f"| #{f.index} | `{f.function_name}` | `{f.offset}` | `{f.module or 'kernel'}` |"
                    )
                lines.append("")
            lines.append("## 3. 根因分析與除錯清單（Root Cause Analysis & Debug Checklist）")
            lines.append(f"```text\n{_localize_analysis_text(kp.root_cause_analysis)}\n```\n")
            for chk in kp.actionable_checklist:
                lines.append(f"- [ ] {_localize_checklist_item(chk)}")
        elif report.arm_hardfault:
            hf = report.arm_hardfault
            lines.append("## 1. HardFault 暫存器（HardFault Registers）")
            lines.append(f"- **HFSR**: `0x{hf.hfsr_raw:08X}`")
            lines.append(
                f"- **CFSR**: `0x{hf.cfsr_raw:08X}` (UFSR: `0x{hf.ufsr_raw:04X}`, BFSR: `0x{hf.bfsr_raw:02X}`, MMFSR: `0x{hf.mmfsr_raw:02X}`)"
            )
            if hf.pc_faulting is not None:
                lines.append(f"- **故障 PC（Faulting PC）**: `0x{hf.pc_faulting:08X}`")
            if hf.bfar_raw is not None:
                lines.append(f"- **故障位址暫存器（BFAR）**: `0x{hf.bfar_raw:08X}`")
            if hf.mmfar_raw is not None:
                lines.append(f"- **記憶體管理故障位址（MMFAR）**: `0x{hf.mmfar_raw:08X}`")
            lines.append("")
            lines.append("## 2. Fault Flags 與根因（Fault Flags & Root Cause）")
            for fl in hf.fault_flags:
                lines.append(f"- ⚠️ {_localize_fault_flag(fl)}")
            lines.append(f"\n```text\n{_localize_hardfault_summary(hf.root_cause_analysis)}\n```\n")
            for chk in hf.actionable_checklist:
                lines.append(f"- [ ] {_localize_checklist_item(chk)}")
        else:
            lines.extend(
                [
                    "## 1. 未辨識 Crash Signature（Unsupported Crash Signature）",
                    "- **狀態（Status）**: 未偵測到已支援的 Kernel Panic / HardFault 標記。",
                    f"- **原始日誌行數（Raw Log Lines）**: `{report.raw_log_lines}`",
                    "",
                    "## 2. 建議下一步（Next Step）",
                    "- 保留完整 UART log，確認內容包含 Kernel Panic、Oops、HardFault 或相關暫存器標記。",
                ]
            )

        effective_timing = timing or getattr(report, "timing", None)
        if effective_timing is not None:
            lines.append("")
            lines.append("## UART 時序分析（UART Timing Analysis）")
            lines.append(
                f"- **總記錄時間（Total Log Duration）**: `{f'{effective_timing.total_log_duration_s:.3f} 秒' if effective_timing.total_log_duration_s is not None else 'N/A'}`"
            )
            lines.append(f"- **原始日誌行數（Line Count）**: `{effective_timing.line_count} 行`")
            lines.append(
                f"- **時間戳覆蓋率（Timestamp Coverage）**: `{effective_timing.timestamp_coverage * 100:.1f}%`"
            )
            lines.append("- **開機階段耗時（Boot Phase Durations）**:")
            bl_dur = effective_timing.boot_phase_durations.get("bootloader")
            k_dur = effective_timing.boot_phase_durations.get("kernel")
            us_dur = effective_timing.boot_phase_durations.get("userspace")
            lines.append(
                f"  - **Bootloader**: `{f'{bl_dur:.3f} 秒' if bl_dur is not None else 'N/A'}`"
            )
            lines.append(f"  - **Kernel**: `{f'{k_dur:.3f} 秒' if k_dur is not None else 'N/A'}`")
            lines.append(
                f"  - **Userspace**: `{f'{us_dur:.3f} 秒' if us_dur is not None else 'N/A'}`"
            )
            if effective_timing.crash_to_reset_interval_s is not None:
                lines.append(
                    f"- **崩潰至重置間隔（Crash-to-Reset Interval）**: `{effective_timing.crash_to_reset_interval_s:.3f} 秒`"
                )

        symptom_lines = source_lines if source_lines is not None else _report_symptom_lines(report)
        _append_symptom_classification(lines, classify_symptoms(symptom_lines))

        return "\n".join(lines)


def _report_symptom_lines(report: UARTReport) -> list[str]:
    """Build a small evidence set when the original UART lines are unavailable."""
    evidence: list[str] = [report.summary_title]
    if report.kernel_panic:
        evidence.extend(
            [
                report.kernel_panic.panic_reason,
                report.kernel_panic.root_cause_analysis,
                *report.kernel_panic.actionable_checklist,
            ]
        )
    if report.arm_hardfault:
        evidence.extend(
            [
                report.arm_hardfault.root_cause_analysis,
                *report.arm_hardfault.fault_flags,
                *report.arm_hardfault.actionable_checklist,
            ]
        )
    return [line for line in evidence if line]


def _escape_markdown(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _append_symptom_classification(lines: list[str], matches: list[MatchedSymptom]) -> None:
    lines.append("")
    lines.append("## UART 症狀分類（UART Symptom Classification）")
    if not matches:
        lines.append("未偵測到症狀（No known symptoms detected）。")
        return
    lines.extend(
        [
            "| 類別（Category） | 嚴重度（Severity） | 描述（Description） | 日誌行（Matched Line） | 建議行動（Suggested Action） |",
            "|---|---|---|---|---|",
        ]
    )
    for match in matches:
        symptom = match.symptom
        description = f"{symptom.description_zh} ({symptom.description_en})"
        action = f"{symptom.suggested_action_zh} ({symptom.suggested_action_en})"
        matched_line = f"L{match.line_number}: {match.matched_line}"
        lines.append(
            "| "
            f"`{_escape_markdown(symptom.category)}` | "
            f"`{symptom.severity}` | "
            f"{_escape_markdown(description)} | "
            f"`{_escape_markdown(matched_line)}` | "
            f"{_escape_markdown(action)} |"
        )
